package local:sandbox;

world sandbox {
  import local:host/host-impl;
  import local:ts-utils/ts-utils-impl;
  record sandbox-options {
    strip-types: bool,
    filename: option<string>,
  }
  export evaluate-module: func(code: string, method: string, args: list<string>, options: sandbox-options);
  export evaluate: func(code: string, args: list<string>, options: sandbox-options);
}