package root:component;

world root {

  export evaluate-module: func(code: string, method: string, args: list<string>, strip-types: bool);
  export evaluate: func(code: string, args: list<string>, stip-types: bool);
}
